# Helm chart values
karpenter:
  serviceAccount:
    create: true
  nodeSelector:
    kubernetes.io/os: linux
  settings:
    aws:
      clusterName: eks-gitops
      clusterEndpoint: https://3DB0A735753BDB78B966BA5B79FDAEA0.gr7.us-west-2.eks.amazonaws.com
      defaultInstanceProfile: arn:aws:iam::504907951892:instance-profile/karpenter-blueprints_4067990795380418201
      interruptionQueueName: eks-gitops
